Controllers/BlogPostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AstraBlog.Data;
using AstraBlog.Models;
using Microsoft.AspNetCore.Authorization;
using AstraBlog.Services.Interfaces;
using AstraBlog.Helpers;

namespace AstraBlog.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BlogPostsController : Controller
    {
        private readonly IImageService _imageService;
        private readonly IAstraBlogService _blogPostService;

        public BlogPostsController(ApplicationDbContext context, IImageService imageService, IAstraBlogService blogPostService)
        {
            _imageService = imageService;
            _blogPostService = blogPostService;
        }

        public async Task<IActionResult> AdminPage()
        {
            var blogPosts = await _blogPostService.GetBlogPostsAsync();
            return View(blogPosts);
        }

        public async Task<IActionResult> ManagePosts()
        {
            var blogPosts = await _blogPostService.GetBlogPostsAsync();
            return View(blogPosts);
        }

        // GET: BlogPosts/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(string? slug)
        {
            if (string.IsNullOrEmpty(slug))
            {
                return NotFound();
            }

            var blogPost = await _blogPostService.GetBlogPostAsync(slug);

            if (blogPost == null)
            {
                return NotFound();
            }

            return View(blogPost);
        }

        // GET: BlogPosts/Create
        public async Task<IActionResult> Create()
        {
            ViewData["CategoryId"] = new SelectList(await _blogPostService.GetCategoriesAsync(), "Id", "Name");
            //TODO: Add Tags to choose from


            return View(new BlogPost());
        }

        // POST: BlogPosts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Abstract,Content,Created,Updated,Slug,IsDeleted,Status,ImageFile,CategoryId")] BlogPost blogPost, string? stringTags)
        {

            ModelState.Remove("Slug");

            if (ModelState.IsValid)
            {
                // Slug BlogPost
                if (!await _blogPostService.ValidateSlugAsync(blogPost.Title!, blogPost.Id))
                {
                    ModelState.AddModelError("Title", "A similar Title or Slug is already in use.");

                    ViewData["CategoryId"] = new SelectList(await _blogPostService.GetCategoriesAsync(), "Id", "Name");
                    return View(blogPost);
                }
                blogPost.Slug = StringHelper.BlogSlug(blogPost.Title!);


                // Format Date(s)
                blogPost.Created = DataUtility.GetPostGresDate(DateTime.UtcNow);

                // Image Service
                if (blogPost.ImageFile != null)
                {
                    blogPost.ImageData = await _imageService.ConvertFileToByteArrayAsync(blogPost.ImageFile);
                    blogPost.ImageType = blogPost.ImageFile.ContentType;
                }

                //TODO: Call Service to Save New BlogPost
                await _blogPostService.AddBlogPostAsync(blogPost);


                //TODO: Add Tag(s) to BlogPost
                if (!string.IsNullOrWhiteSpace(stringTags))
                {
                    IEnumerable<string> tags = stringTags.Split(",").ToList();
                    await _blogPostService.AddTagsToBlogPostAsync(tags, blogPost.Id);
                }


                return RedirectToAction("Index","Home");
            }


            ViewData["CategoryId"] = new SelectList(await _blogPostService.GetCategoriesAsync(), "Id", "Name");
            return View(blogPost);
        }

        // GET: BlogPosts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blogPost = await _blogPostService.GetBlogPostAsync(id.Value);

            if (blogPost == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(await _blogPostService.GetCategoriesAsync(), "Id", "Name", blogPost.CategoryId);
            return View(blogPost);
        }

        // POST: BlogPosts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Abstract,Content,Created,Updated,Slug,IsDeleted,Status,ImageFile,ImageData,ImageType,CategoryId")] BlogPost blogPost, string? stringTags)
        {
            if (id != blogPost.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // Dates Example
                    blogPost.Created = DataUtility.GetPostGresDate(blogPost.Created);
                    blogPost.Updated = DataUtility.GetPostGresDate(DateTime.UtcNow);

                    // Image Service
                    if (blogPost.ImageFile != null)
                    {
                        blogPost.ImageData = await _imageService.ConvertFileToByteArrayAsync(blogPost.ImageFile);
                        blogPost.ImageType = blogPost.ImageFile.ContentType;
                    }

                    // Slug BlogPost
                    if (!await _blogPostService.ValidateSlugAsync(blogPost.Title!, blogPost.Id))
                    {
                        ModelState.AddModelError("Title", "A similar Title or Slug is already in use.");

                        ViewData["CategoryId"] = new SelectList(await _blogPostService.GetCategoriesAsync(), "Id", "Name");
                        return View(blogPost);
                    }
                    blogPost.Slug = StringHelper.BlogSlug(blogPost.Title!);

                    // Call Service to Update BlogPost
                    await _blogPostService.UpdateBlogPostAsync(blogPost);


                    // Edit Tags
                    if (!string.IsNullOrWhiteSpace(stringTags))
                    {
                        IEnumerable<string> tags = stringTags.Split(",").ToList();
                        await _blogPostService.AddTagsToBlogPostAsync(tags, blogPost.Id);
                    }


                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await BlogPostExists(blogPost.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(AdminPage));
            }
            ViewData["CategoryId"] = new SelectList(await _blogPostService.GetCategoriesAsync(), "Id", "Name", blogPost.CategoryId);
            return View(blogPost);
        }

        // GET: BlogPosts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blogPost = await _blogPostService.GetBlogPostAsync(id.Value);

            if (blogPost == null)
            {
                return NotFound();
            }

            return View(blogPost);
        }

        // POST: BlogPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var blogPost = await _blogPostService.GetBlogPostAsync(id);

            if (blogPost != null)
            {
                await _blogPostService.DeleteBlogPostAsync(blogPost);
            }

            return RedirectToAction(nameof(AdminPage));
        }

        private async Task<bool> BlogPostExists(int id)
        {
            return (await _blogPostService.GetBlogPostsAsync()).Any(b => b.Id == id);
        }
    }
}

Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AstraBlog.Data;
using AstraBlog.Models;
using AstraBlog.Services.Interfaces;
using AstraBlog.Services;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace AstraBlog.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoriesController : Controller
    {
        private readonly IImageService _imageService; 
        private readonly IAstraBlogService _blogPostService;

        public CategoriesController(IAstraBlogService blogPostService, 
                                    IImageService imageService)
        {
            _blogPostService = blogPostService;
            _imageService = imageService;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            return View(await _blogPostService.GetCategoriesAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id, int? pageNum = null)
        {
            if (id == null)
            {
                return NotFound();
            }

            Category category = await _blogPostService.GetCategoryAsync(id.Value);

            if (category == null)
            {
                return NotFound();
            }

            ViewData["PageNum"] = pageNum;  

            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,ImageFile")] Category category)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // Validate required fields
                    if (string.IsNullOrWhiteSpace(category.Name))
                    {
                        ModelState.AddModelError("Name", "Category name is required");
                        return View(category);
                    }

                    // Image Service
                    if (category.ImageFile != null)
                    {
                        // Validate file type
                        var validTypes = new[] { "image/jpeg", "image/png", "image/gif" };
                        if (!validTypes.Contains(category.ImageFile.ContentType))
                        {
                            ModelState.AddModelError("ImageFile", "Please upload a valid image file (JPEG, PNG, or GIF)");
                            return View(category);
                        }

                        // Validate file size (max 5MB)
                        if (category.ImageFile.Length > 5 * 1024 * 1024)
                        {
                            ModelState.AddModelError("ImageFile", "File size must be less than 5MB");
                            return View(category);
                        }

                        try
                        {
                            category.ImageData = await _imageService.ConvertFileToByteArrayAsync(category.ImageFile);
                            category.ImageType = category.ImageFile.ContentType;
                        }
                        catch (Exception ex)
                        {
                            ModelState.AddModelError("ImageFile", "Error processing image: " + ex.Message);
                            return View(category);
                        }
                    }

                    await _blogPostService.AddCategoryAsync(category);   
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "An error occurred while creating the category: " + ex.Message);
                    return View(category);
                }
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _blogPostService.GetCategoryAsync(id.Value);

            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,ImageData,ImageType")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    // Image Service
                    if (category.ImageFile != null)
                    {
                        category.ImageData = await _imageService.ConvertFileToByteArrayAsync(category.ImageFile);
                        category.ImageType = category.ImageFile.ContentType;
                    }

                    await _blogPostService.UpdateCategoryAsync(category);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await CategoryExists(category.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _blogPostService.GetCategoryAsync(id.Value);

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            var category = await _blogPostService.GetCategoryAsync(id);

            if (category != null)
            {
                await _blogPostService.DeleteCategoryAsync(category);
            }
            
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> CategoryExists(int id)
        {
          return (await _blogPostService.GetCategoriesAsync()).Any(c => c.Id == id);
        }
    }
}

Views/Shared/_AuthorArea.cshtml
<!-- Start Author Area  -->
<div class="axil-author-area axil-author-banner bg-color-grey">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="about-author">
                    <div class="media">
                        <div class="thumbnail">
                            <a href="#" style="height:50%;width:50%">
                                <img src="~/img/DefaultUserImage.png" alt="Author Images" style="height:150px;width:150px">
                            </a>
                        </div>
                        <div class="media-body">
                            <div class="author-info">
                                <h1 class="title"><a href="#">Blog Author</a></h1>
                                <span class="b3 subtitle">Sr. Dev</span>
                            </div>
                            <div class="content">
                                <p class="b1 description">
                                    My favorite compliment is being told that I look like my dad.
                                    Seeing myself in her image, like this son up top, makes me so proud of how
                                    far I’ve come, and so thankful for where I come from
                                </p>
                                <ul class="social-share-transparent size-md">
                                    <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                                    <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                                    <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                                    <li><a href="#"><i class="far fa-envelope"></i></a></li>
                                    <li><a href="#"><i class="fab fa-linkedin-in"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Author Area  -->

Views/Shared/_BlogCard.cshtml
@model BlogPost

@using AstraBlog.Services.Interfaces
@using AstraBlog.Enums

@inject IImageService _ImageService
@inject IAstraBlogService _BlogService


<!-- Start Post List  -->
<div class="content-block post-list-view mt--30">
    <div class="post-thumbnail">
        <a asp-action="Details" asp-controller="BlogPosts" asp-route-slug="@Model.Slug">
            <img src="@_ImageService.ConvertByteArrayToFile(Model.ImageData!,Model.ImageType!,(int)DefaultImage.BlogPostImage)" alt="Post Images">
        </a>
    </div>
    <div class="post-content">
        <div class="post-cat">
            <div class="post-cat-list">
                <a class="hover-flip-item-wrapper" href="#">
                    <span class="hover-flip-item">
                        <span data-text="@Model.Category!.Name">@Model.Category!.Name</span>
                    </span>
                </a>
            </div>
        </div>
        <h4 class="title">
            <a asp-action="Details" asp-controller="BlogPosts" asp-route-slug="@Model.Slug">
                @Model.Title
            </a>
        </h4>
        <div class="post-meta-wrapper">
            <div class="post-meta">
                <div class="content">
                    <h6 class="post-author-name">
                        <a class="hover-flip-item-wrapper" href="author.html">
                            <span class="hover-flip-item">
                                <span data-text="Blog Author">Blog Author</span>
                            </span>
                        </a>
                    </h6>
                    <ul class="post-meta-list">
                        <li>@Model.Created.ToString("MMM dd, yyyy")</li>
                        @*<li>3 min read</li>*@
                    </ul>
                </div>
            </div>
            @if (User.IsInRole("Admin"))
            {
                <ul class="social-share-transparent justify-content-end">
                    <li><a asp-action="Edit" asp-controller="BlogPosts" asp-route-id="@Model.Id"><i class="fa-solid fa-file-pen fa-lg"></i></a></li>
                    <li><a asp-action="Details" asp-controller="BlogPosts" asp-route-id="@Model.Id" asp-route-slug="@Model.Slug"><i class="fa-solid fa-file-invoice fa-lg"></i></a></li>
                    <li><a asp-action="Delete" asp-controller="BlogPosts" asp-route-id="@Model.Id"><i class="fa-solid fa-trash-can fa-lg"></i></a></li>
                </ul>
            }
        </div>
    </div>
</div>
<!-- End Post List  -->

Views/Shared/_Layout - Copy.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AstraBlog</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AstraBlog.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AstraBlog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AstraBlog - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LoginLayout.cshtml
<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Maintanence || Blogar - Personal Blog Template</title>
    <meta name="robots" content="noindex, follow" />
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="~/assets/images/favicon.png">

    <!-- CSS
    ============================================ -->
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/assets/css/vendor/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/css/vendor/font-awesome.css">
    <link rel="stylesheet" href="~/assets/css/vendor/slick.css">
    <link rel="stylesheet" href="~/assets/css/vendor/slick-theme.css">
    <link rel="stylesheet" href="~/assets/css/vendor/base.css">
    <link rel="stylesheet" href="~/assets/css/plugins/plugins.css">
    <link rel="stylesheet" href="~/assets/css/style.css">

</head>

<body>
    <div class="main-wrapper">
        <div id="my_switcher" class="my_switcher">
            <ul>
                <li>
                    <a href="javascript: void(0);" data-theme="light" class="setColor light">
                        <span title="Light Mode">Light</span>
                    </a>
                </li>
                <li>
                    <a href="javascript: void(0);" data-theme="dark" class="setColor dark">
                        <span title="Dark Mode">Dark</span>
                    </a>
                </li>
            </ul>
        </div>
        <!-- Start Maintanence Area  -->
        <div class="">
            <div class="container">
                <div class="row align-items-center">
                    <div class="order-2 order-lg-1 col-lg-6 mt_md--40 mt_sm--40">
                        <div class="content">
                            @*<div class="logo">
                                <a href="index.html">
                                    <img class="dark-logo" src="~/assets/images/logo/logo-black.png" alt="Logo Images">
                                    <img class="light-logo" src="~/assets/images/logo/logo-white2.png" alt="Logo Images">
                                </a>
                            </div>*@
                            @RenderBody()

                        </div>
                    </div>
                    <div class="order-1 order-lg-2 col-lg-5 offset-lg-1">
                        <div class="thumbnail">
                            <img src="~/img/istockphoto-1281150061-612x612.jpg" alt="Images">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Maintanence Area  -->
        <!-- Start Back To Top  -->
        <a id="backto-top"></a>
        <!-- End Back To Top  -->
    </div>

    <!-- JS
    ============================================ -->
    <!-- Modernizer JS -->
    <script src="~/assets/js/vendor/modernizr.min.js"></script>
    <!-- jQuery JS -->
    <script src="~/assets/js/vendor/jquery.js"></script>
    <!-- Bootstrap JS -->
    <script src="~/assets/js/vendor/bootstrap.min.js"></script>
    <script src="~/assets/js/vendor/slick.min.js"></script>
    <script src="~/assets/js/vendor/tweenmax.min.js"></script>
    <script src="~/assets/js/vendor/js.cookie.js"></script>
    <script src="~/assets/js/vendor/jquery.style.switcher.js"></script>


    <!-- Main JS -->
    <script src="~/assets/js/main.js"></script>
    @await RenderSectionAsync("scripts", required:false)
</body>

</html>

Views/Shared/_LogoutPartial.cshtml
<form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
</form>

Views/Shared/_Sidebar.cshtml
@using AstraBlog.Services.Interfaces
@using AstraBlog.Enums

@inject IImageService _ImageService
@inject IAstraBlogService _BlogService

<!-- Start Sidebar Area  -->
<div class="sidebar-inner">

    <!-- Start Single Widget  -->
    <div class="axil-single-widget widget widget_categories mb--30">
        <ul>
            @foreach (Category category in (await _BlogService.GetCategoriesAsync()).Take(4))
            {
                <li class="cat-item">
                    <a asp-action="Details" asp-controller="Categories" asp-route-id="@category.Id" class="inner">
                        <div class="thumbnail">
                            <img src="@_ImageService.ConvertByteArrayToFile(category.ImageData!,category.ImageType!,(int)DefaultImage.CategoryImage)" alt="">
                        </div>
                        <div class="content">
                            <h5 class="title">@category.Name</h5>
                        </div>
                    </a>
                </li>
            }
        </ul>
    </div>
    <!-- End Single Widget  -->
    <!-- Start Single Widget  -->
    <div class="axil-single-widget widget widget_postlist mb--30">
        <h5 class="widget-title">Popular on Astra</h5>
        <!-- Start Post List  -->
        <div class="post-medium-block">

            @foreach (BlogPost blogPost in (await _BlogService.GetPopularPostsAsync(3)))
            {
                <!-- Start Single Post  -->
                <div class="content-block post-medium mb--20">
                    <div class="post-thumbnail">
                        <a href="post-details.html">
                            <img src="@_ImageService.ConvertByteArrayToFile(blogPost.ImageData!,blogPost.ImageType!,(int)DefaultImage.BlogPostImage)" alt="Post Images">
                        </a>
                    </div>
                    <div class="post-content">
                        <h6 class="title">
                            <a asp-controller="BLogPosts" asp-action="Details" asp-route-slug="@blogPost.Slug">
                                @blogPost.Title
                            </a>
                        </h6>
                        <div class="post-meta">
                            <ul class="post-meta-list">
                                <li>@blogPost.Created.ToString("MMM dd, yyyy")</li>
                                <li>10K Likes</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- End Single Post  -->
            }

        </div>
        <!-- End Post List  -->

    </div>
    <!-- End Single Widget  -->

    <!-- Start Single Widget  -->
    <!-- div class="axil-single-widget widget widget_instagram mb--30">
        <h5 class="widget-title">Instagram</h5>

        <ul class="instagram-post-list-wrapper">
            <li class="instagram-post-list">
                <a href="#">
                    <img src="~/assets/images/small-images/instagram-01.jpg" alt="Instagram Images">
                </a>
            </li>
            <li class="instagram-post-list">
                <a href="#">
                    <img src="~/assets/images/small-images/instagram-02.jpg" alt="Instagram Images">
                </a>
            </li>
            <li class="instagram-post-list">
                <a href="#">
                    <img src="~/assets/images/small-images/instagram-03.jpg" alt="Instagram Images">
                </a>
            </li>
            <li class="instagram-post-list">
                <a href="#">
                    <img src="~/assets/images/small-images/instagram-04.jpg" alt="Instagram Images">
                </a>
            </li>
            <li class="instagram-post-list">
                <a href="#">
                    <img src="~/assets/images/small-images/instagram-05.jpg" alt="Instagram Images">
                </a>
            </li>
            <li class="instagram-post-list">
                <a href="#">
                    <img src="~/assets/images/small-images/instagram-06.jpg" alt="Instagram Images">
                </a>
            </li>
        </ul>

    </-->
    <!-- End Single Widget  -->
</div>
<!-- End Sidebar Area  -->